name: Bogang Daily Notice

on:
  schedule:
    - cron: "57 3  * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Debug time
        run: |
          echo "UTC now: $(date -u)"
          echo "KST now: $(TZ=Asia/Seoul date)"

      - name: Call API
        run: |
          curl -fsS https://itple-bogang-bot.vercel.app/api/post-bogang | cat
